#!/usr/bin/env bash

. ./lib/check

usage() {
	echo "
${0} [-h|-g|-f|-t]
	
	-h prints this help
	-g fame goal
	-f fame aquired
	-t type of material (log, ore, fiber, hide, stone)
"
}

while getopts ':hg:f:t:' option; do
	case $option in
		h) 
			usage; exit 0
			;;
		g)
			fameGoal=$OPTARG
			checkNumber "$fameGoal"
			;;
		f)
			fameGot=$OPTARG
			checkNumber "$fameGot"
			;;
		t)
			item=$OPTARG
			;;
		?)
			usage; exit 0
			;;
	esac
done

fameGoal=$((fameGoal - fameGot))
checkNumber "$fameGoal"

while IFS=, read -r tier log ore fiber hide stone fame; do
	required=$(( fameGoal / fame ))
	if ! [[ $(( fameGoal % fame )) == 0 ]]; then
		required=$((required + 1))
	fi
	
	case "$item" in
		log)
			echo "$tier: amount required $log $required"
			;;
		ore)
			echo "$tier: amount required $ore $required"
			;;
		fiber)
			echo "$tier: amount required $fiber $required"
			;;
		hide)
			echo "$tier: amount required $hide $required"
			;;
		stone)
			echo "$tier: amount required $stone $required"
			;;
	esac
done < ~/MyCommands/LinuxCommands/dict/albion/albionGathering
