#!/usr/bin/env bash

greet() {
	local name=$1
	echo "hello $name"
}

goodbye() {
	local name=$1
	echo "goodbye $name"
}

if ! (return 2>/dev/null); then
	# we are being called directly
	greet dave
	goodbye john
fi
